---
title: "Experience and Publications"
---

## Experience
1. **Biostatistics Research Intern - USC Alzheimer's Therapeutic Research Institute **  
   - Conducted comprehensive analysis of clinical trial dataset containing 20,000+ individuals, extracting insights and measuring key
     demographic trends to support research objectives
   - Utilized R for hypothesis testing, data preparation, and statistical modeling to ensure robust analysis
   - Contributed to biostatistics research in understanding underrepresented groups in Alzheimer's pre-clinical trials
   - Optimized inclusive recruitment and retention strategies for AD clinical trials through data-driven methods

2. **Data Analyst - Daily Nexus**  
   - Collected and analyzed data with Python and SQL for data cleaning and exploratory modeling
   - Create interesting, data-driven content for the student-run newspaper
   - Design compelling data visualizations using Tableau, Datawrapper, and Canva to communicate complex findings
   - Interpret complicated data for accessibility of non-scientific readers

3. **Data Science Researcher - Soojin Yi Lab**  
   - Analyze genome sequence composition to understand biological diversity utilizing R and
Python
   - Construct and test phylogenetic relationships across species using Bayesian and     maximum likelihood models
   - Utilize Gaussian Mixture Models for probabilistic classification and summarization of methylation presence in genes
   - Investigate DNA methylation and functional differences in invertebrate animals

4. **Undergraduate Learning Assistant - UC Santa Barbara PSTAT and Computer Science Department**  
   - Hold office hours for 250+ students, clearly communicating complex technical concepts
   - Aid students in understanding course material, simplifying technical material and demonstrating strong communication skills
   - Provide assistance and support to professor and students during lecture
   - Lead tutoring sessions and discussion sections

5. **Assistant Statistics & Data Science Program Coordinator - UC Santa Barbara PSTAT Department**  
   - Designed and developed the department’s scholarship website, improving accessibility of program and application information
   - Automate data processing and workflow tasks using R/Python to improve efficiency and reduce manual workload across projects
   - Analyze event data and participant feedback to evaluate program effectiveness and inform improvements
   - Generate reports and summary statistics on attendance, engagement, and outcomes to support data-driven decision-making
- Organized and maintained structured event records and administrative datasets for efficient planning and reporting

6. **UI/UX Designer - SB Creative Lab**  
   - Developed mobile application for Blender's smoothie chain by integrating customer data insights to enhance user experience and
     inform product strategy
   - Research, gather data on customers needs and behaviors for Blender's and other food service apps
   - Advance interpersonal and communication skills in a group setting
   - Utilized Figma to design an efficient and accessible platform

## Publications
1. **"A deep dive into campus sustainability: UCSB reduces carbon footprint by 67% since 1990"**  
   - Published in UCSB’s *Daily Nexus* (Winter 2025).  
